mysql:
  url: 172.19.0.12
  port: 3306
  username: root #your_mysql_userName
  password: cc.+-0109 #your_mysql_passWord
  dbname: douyin

oss:
  endpoint: oss-cn-shanghai.aliyuncs.com
  accessKeyID: #请填充
  accessKeySecret: #请填充
  bucketName: simple-douyin-cong
